"""Add updated_at column to CartItems

Revision ID: 95c522320d61
Revises: 
Create Date: 2025-09-11 11:13:56.479999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95c522320d61'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CartItems', sa.Column('updated_at', sa.DateTime(), nullable=True), )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CartItems', 'updated_at')
    # ### end Alembic commands ###
