"""add admin_id to Product

Revision ID: ff66f648b591
Revises: 95c522320d61
Create Date: 2025-09-22 18:19:47.910325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff66f648b591'
down_revision: Union[str, Sequence[str], None] = '95c522320d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Cart', 'total_price',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('CartItems', 'subtotal',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('CartItems', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.add_column('Product', sa.Column('admin_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Product', 'User', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Product', type_='foreignkey')
    op.drop_column('Product', 'admin_id')
    op.alter_column('CartItems', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('CartItems', 'subtotal',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('Cart', 'total_price',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
